"""add_service_requests_table

Revision ID: e447c8a3f9b7
Revises: 4b715631d65e
Create Date: 2026-06-09 10:12:51.736561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e447c8a3f9b7'
down_revision: Union[str, Sequence[str], None] = '4b715631d65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('desired_schedule', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'matched', 'completed', 'cancelled', name='service_request_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # autogen 누락 보정: drop_table은 PG enum 타입을 제거하지 않는다 →
    # 명시적으로 drop 하지 않으면 재upgrade 시 "type already exists"로 실패.
    sa.Enum(name='service_request_status').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
